### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by shivamshinde123** [shivamshinde123/Scania-Truck-Failures-Prediction#1]
<strong style="color:#8D3DAF;">Inital Setup and Work</strong>

- [x] Creating a new conda environment
- [x] Installing necessary libraries
- [x] Creating a project structure using cookiecutter or manually
- [x] #2

**Comment by shivamshinde123** [comment]
Completed basic setup and work
